* Introduction

Welcome to my emacs configuration.

This should set up emacs as I like it anywhere I need it.

The idea for this configuration (and some of the defuns) are blatantly
stolen or adapted from the [[https://github.com/eschulte/emacs24-starter-kit/][Emacs Starter Kit]].  The main reason why I
do this myself instead of using ESK itself is I want to work a bit
with emacs lisp and I want to set every thing precisely as I mean it.
You should probably use that, anyway.

** Caveats
   + You should get the latest available emacs. I'm on 26.1 right now,
     so I know this works for that version.

   + If on the Mac, use a Cocoa version. I had issues with deadkeys,
     fullscreen, etc. with other versions. You could try out
     [[http://emacsformacosx.com/][Emacs for MacOS X]] or [[https://github.com/d12frosted/homebrew-emacs-plus][Emacs Plus]].


* Implementation
Configuration is modular, but in some cases, things could depend on
each other. Order (possibly) matters.

It should be easy to turn on and off features by commenting here the
sections you don't need.

Some sections, you should just jeep. I say when that is the
case. Stuff might break below otherwise.

** Initialization
   This section is for bootstrapping the setup. It holds various
   settings that are specific to the configuration system, rather than
   providing features or changing behaviours.
   #+begin_src emacs-lisp
     (load-init-file "bootstrap")
   #+end_src

** Visuals
   This section sets up visual preferences for Emacs as a whole. It
   sets up things like the theme to use, the base font, the
   colorspace, etc.
   #+begin_src emacs-lisp
     (load-init-file "visuals")
   #+end_src

** General behaviours
   This section defines some default behaviours for the whole Emacs
   experience.
   #+begin_src emacs-lisp
     (load-init-file "general")
   #+end_src

** Keeping state
   This section sets up state keeping, backups and so on.
   #+begin_src emacs-lisp
     (load-init-file "state")
   #+end_src

** OS-specific config
   Here we setup operating-system specific configuration. Right now,
   there is only "specialized" MacOS configuration.
   #+begin_src emacs-lisp
     (load-init-file "macos")
   #+end_src

** Dired
   In this section we configure Dired, the directory explorer of Emacs.
   #+begin_src emacs-lisp
     (load-init-file "dired")
   #+end_src

** Prog mode
   In this section, we setup Emacs for writing code. Prog is for
   generic programming config, then a file per programming language I
   care about.
   #+begin_src emacs-lisp
     (load-init-file "prog")
   #+end_src



** Customize
   Last thing is load customizations.  This goes last to allow user overridings through customize.
   #+begin_src emacs-lisp
     (if (file-exists-p custom-file) (load custom-file))
   #+end_src
