* Ruby configuration

Ruby is an awesome language.  Here, we configure Emacs to be the best Ruby editor ever.

** Flymake
   Setup flymake for Ruby
   #+begin_src emacs-lisp
     (i-require 'flymake-ruby)
     (add-hook 'ruby-mode-hook 'flymake-ruby-load)
   #+end_src

** Indentation
   The default indentation system attempts to align the arguments of a
   function with the opening bracket vertically.  Turn this off and
   revert to normal indentation.
   #+begin_src emacs-lisp
     (setq ruby-deep-indent-paren nil)
   #+end_src

** Inf Ruby
   Start a Ruby REPL with =C-c r r=
   #+begin_src emacs-lisp
     (i-require 'inf-ruby)
     (global-set-key (kbd "C-c r r") 'inf-ruby)
   #+end_src

** RVM integration
   Run the correct rvm instance with =C-c r a=
   #+begin_src emacs-lisp
     (i-require 'rvm)
     (global-set-key (kbd "C-c r a") 'rvm-activate-corresponding-ruby)
   #+end_src

** Bundler integration
   - Run bundler commands from within Emacs
     #+begin_src emacs-lisp
       (i-require 'bundler)
       (global-set-key (kbd "C-c r b i") 'bundle-install)
       (global-set-key (kbd "C-c r b u") 'bundle-update)
       (global-set-key (kbd "C-c r b c") 'bundle-console)
       (global-set-key (kbd "C-c r b o") 'bundle-open)

     #+end_src
** Projectile Rails integration
   We use Projectile for software projects.  Extend it with the specialized =projectile-rails= mode when doing RoR
   #+begin_src emacs-lisp
     (i-require 'projectile-rails)
     (add-hook 'projectile-mode-hook 'projectile-rails-on)
   #+end_src

** Robe
   Robe is like Rope but for Ruby
   #+begin_src emacs-lisp
     (i-require 'robe)
     (add-hook 'ruby-mode-hook 'robe-mode)
     (defadvice inf-ruby-console-auto (before activate-rvm-for-robe activate)
       (rvm-activate-corresponding-ruby))
   #+end_src

   We can also use Company mode with Robe
   #+begin_src emacs-lisp
     (i-require 'company)
     (global-company-mode t)
     (push 'company-robe company-backends)
   #+end_src
** Ruby-dev
   Pry integration with Emacs
   #+begin_src emacs-lisp
     (i-require 'ruby-dev)
     (autoload 'turn-on-ruby-dev "ruby-dev" nil t)
     (add-hook 'ruby-mode-hook 'turn-on-ruby-dev)
   #+end_src
